[colours]
action_key = ""

[colours.available-mirrors]
heading = ""
border = ""
highlight = ""
reverse = false

[colours.countries]
heading = ""
border = ""
highlight = ""
reverse = false

[colours.mirrors]
heading = ""
border = ""
reverse = false

[colours.info]
app = ""
os = ""
countries = ""
mirrors = ""
last_checked = ""
now = ""

[icons]
os = ""
countries = ""
mirrors = ""
last_checked = ""
now = ""
